name: Build and Run Flask Docker

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up .env
      run: |
        echo "APP_MESSAGE=${{ secrets.APP_MESSAGE }}" >> .env
        echo "APP_HEALTH=${{ secrets.APP_HEALTH }}" >> .env

    - name: Build Docker image
      run: docker build -t my_flask_app .

    - name: Run Docker container
      run: docker run -d -p 5000:5000 --env-file .env my_flask_app

    - name: Debug .env
      run: cat .env
